<<<<<<< HEAD
# SOF west manifest
manifest:
  version: "0.13"

  defaults:
    remote: thesofproject

  remotes:
    - name: thesofproject
      url-base: https://github.com/thesofproject
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: rimage
      repo-path: rimage
      path: sof/rimage
      revision: 02abc5d342a3ee6965bdc933ea1439d85d0256da

    - name: tomlc99
      repo-path: tomlc99
      path: sof/rimage/tomlc99
      revision: e3a03f5ec7d8d33be705c5ce8a632d998ce9b4d1

    - name: zephyr
      repo-path: zephyr
      revision: 8e55e59c5917b61d563d5e8bf759e8aeb746ff8b
      remote: zephyrproject
      # Import some projects listed in zephyr/west.yml@revision
      #
      # Warning: changes to zephyr/west.yml or to any other _imported_
      # west.yml file are _ignored_ by design!  Only the above
      # 'revision:' of zephyr/west.yml is used.
      import:
        name-whitelist:
          - hal_xtensa
          - mbedtls
          - mipi-sys-t
          - lz4
          - tinycrypt

  self:
    path: sof
    # Changes to submanifests/*.yml files _are_ effective; these have no
    # specified 'revision:'
    import: submanifests
=======
# SOF specific manifest

manifest:
  defaults:
    remote: zephyr-upstream

  remotes:
    - name: intel
      url-base: https://github.com/intel-innersource
    - name: zephyr-upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: sof
      url-base: https://github.com/thesofproject


  #
  # Please add items below based on alphabetical order
  projects:
    - name: zephyr-intel
      repo-path: os.rtos.zephyr.zephyr-intel
      path: zephyr-intel
      revision: 8ef0bdf2c420edbb56a0b5ae8db5794a741aa010
      remote: intel
      import:
        name-whitelist:
          - zephyr
          - ci-tools
          - cmsis
          - civetweb
          - fatfs
          - hal_st
          - hal_xtensa
          - littlefs
          - mbedtls
          - mipi-sys-t
          - net-tools
          - segger
          - tinycbor
          - tinycrypt
          - nanopb
          - tflite-micro
          - lz4
          - hal-intel

    - name: rimage
      repo-path: drivers.audio.firmware.rimage
      path: drivers.audio.firmware.converged/rimage
      revision: 452847ddc04ebf865e3e03926cc3298db4b66a81
      remote: intel
      # import: true

    - name: tomlc99
      repo-path: tomlc99
      path: drivers.audio.firmware.converged/rimage/tomlc99
      revision: e3a03f5ec7d8d33be705c5ce8a632d998ce9b4d1
      remote: sof

  self:
    path: drivers.audio.firmware.converged
    west-commands: scripts/west-commands.yml
>>>>>>> 80e87bec2 ([DO NOT UPSTREAM] Add west.yaml configuring zephyr dependencies from sof)
